version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - echo "Nothing to install ....."

  build:
    commands:
      - echo " Nothing to build ...."
      - echo $CODEBUILD_SRC_DIR
           
  post_build:
    commands:
      - echo "Deployment complete !!!!!!!!"
